apiVersion: datadoghq.com/v2alpha1
kind: DatadogAgent
metadata:
  name: datadog
spec:
  global:
    clusterName: docker-desktop
    kubelet:
      tlsVerify: false
    tags:
      - env:ssi-dev
    credentials:
      apiSecret:
        secretName: datadog-secret
        keyName: api-key
      appSecret:
        secretName: datadog-secret
        keyName: app-key
  override:
    nodeAgent:
      image:
        name: agent
        tag: 7.58.0
      containers:
        trace-agent:
          env:
            - name: DD_APM_COMPUTE_STATS_BY_SPAN_KIND
              value: "true"
            - name: DD_APM_PEER_TAGS_AGGREGATION
              value: "true"
  features:
    admissionController:
      enabled: true
      mutateUnlabelled: false
    # apm:
    #   instrumentation:
    #     enabled: false
        # enabledNamespaces: # Add namespaces to instrument
        # - default
        # libVersions:
        #   java: "1.39.1"
        #   dotnet: "3.3.1"
        #   python: "2.11.7"
        #   js: "5.23.1"
        #   ruby: "2"
    logCollection:
      enabled: true
      containerCollectAll: true
    remoteConfiguration:
      enabled: true
    liveProcessCollection:
      enabled: true
    otlp:
      receiver:
        protocols:
          grpc:
            enabled: true
            endpoint: 0.0.0.0:4317
          http:
            enabled: true
            endpoint: 0.0.0.0:4318