apiVersion: datadoghq.com/v2alpha1
kind: DatadogAgent
metadata:
  name: datadog
spec:
  global:
    clusterName: docker-desktop
    kubelet:
      tlsVerify: false
    tags:
      - env:ssi-dev
    credentials:
      apiSecret:
        secretName: datadog-secret
        keyName: api-key
      appSecret:
        secretName: datadog-secret
        keyName: app-key
  override:
    clusterAgent:
      image:
        #we use this version of the agent to make sure we could use the new SSI features
        tag: 7.64.1
    nodeAgent:
      image:
        tag: 7.64.1
      containers:
        trace-agent:
          env:
            - name: DD_APM_COMPUTE_STATS_BY_SPAN_KIND
              value: "true"
            - name: DD_APM_PEER_TAGS_AGGREGATION
              value: "true"
        agent:
          env:
            - name: "DD_IGNORE_AUTOCONF"
              value: "kube_controller_manager kube_scheduler etcd"
  features:
    #comment out these the following lines if you want to swtich back and use admission controller instead of SSI
    # admissionController:
    #   enabled: true
    #   mutateUnlabelled: false
    apm:
      enabled: true
      #comment out these lines if you want admission controller to use hostip instead of UDS
      hostPortConfig:
        enabled: true
      unixDomainSocketConfig:
        enabled: false
      #comment out these lines if you want to use SSI instead of admission controller
      instrumentation:
        enabled: true
        targets:
          - name: "my target namespace"
            namespaceSelector:
              matchNames:
                - "default"
            ddTraceVersions:
              java: "1.47.3"
              dotnet: "3.13.0"
              python: "3.3.0"
              js: "5.45.0"
    logCollection:
      enabled: true
      containerCollectAll: true
    remoteConfiguration:
      enabled: true
    # clusterChecks:
    #   enabled: true
    #   useClusterChecksRunners: true
    #comment out these lines if you want to configure dogstatsd to use UDP instead of UDS
    dogstatsd:
      hostPortConfig:
        enabled: true
      unixDomainSocketConfig:
        enabled: false
    eventCollection:
      collectKubernetesEvents: true
    liveContainerCollection:
      enabled: true
    liveProcessCollection:
      enabled: true
    npm:
      collectDNSStats: true
      enableConntrack: true
      enabled: true
    otlp:
      receiver:
        protocols:
          grpc:
            enabled: true
            endpoint: 0.0.0.0:4317
          http:
            enabled: true
            endpoint: 0.0.0.0:4318
